//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacturing_Execution_Simulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_BOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ME_BOM()
        {
            this.ME_BOM_DETAILS = new HashSet<ME_BOM_DETAILS>();
            this.ME_SHOP_ORDER = new HashSet<ME_SHOP_ORDER>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ME_BOM_DETAILS> ME_BOM_DETAILS { get; set; }
        public virtual ME_BOM_STATUS ME_BOM_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ME_SHOP_ORDER> ME_SHOP_ORDER { get; set; }
    }
}
