//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacturing_Execution_Simulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_OPERATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ME_OPERATION()
        {
            this.ME_BOM_DETAILS = new HashSet<ME_BOM_DETAILS>();
            this.ME_ROUTING_DETAILS = new HashSet<ME_ROUTING_DETAILS>();
            this.ME_ROUTING_DETAILS1 = new HashSet<ME_ROUTING_DETAILS>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int STATUS { get; set; }
        public string RESOURCE { get; set; }
        public string WORKCENTER { get; set; }
        public string ACTIVITY { get; set; }
        public int RESOURCETYPE { get; set; }
        public string OPERATIONTYPE { get; set; }
    
        public virtual ME_ACTIVITY ME_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ME_BOM_DETAILS> ME_BOM_DETAILS { get; set; }
        public virtual ME_OPERATION_TYPE ME_OPERATION_TYPE { get; set; }
        public virtual ME_RESOURCE ME_RESOURCE { get; set; }
        public virtual ME_RESOURCE_TYPE ME_RESOURCE_TYPE { get; set; }
        public virtual ME_OPERATION_STATUS ME_OPERATION_STATUS { get; set; }
        public virtual ME_WORKCENTER ME_WORKCENTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ME_ROUTING_DETAILS> ME_ROUTING_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ME_ROUTING_DETAILS> ME_ROUTING_DETAILS1 { get; set; }
    }
}
