//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacturing_Execution_Simulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_ROUTING_DETAILS
    {
        public int ID { get; set; }
        public string ROUTING { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public string OPERATION { get; set; }
        public string CONDITION { get; set; }
        public string NEXT_OPERATION { get; set; }
        public string NC_OPERATION { get; set; }
        public int SEMANTIC_ANNOTATION { get; set; }
    
        public virtual ME_OPERATION ME_OPERATION { get; set; }
        public virtual ME_OPERATION ME_OPERATION1 { get; set; }
        public virtual ME_OPERATION_TYPE ME_OPERATION_TYPE { get; set; }
        public virtual ME_ROUTING ME_ROUTING { get; set; }
        public virtual ME_SEMANTIC_ANNOTATION ME_SEMANTIC_ANNOTATION { get; set; }
    }
}
