//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacturing_Execution_Simulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_SHOP_ORDER
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int STATUS { get; set; }
        public int TYPE { get; set; }
        public string PLANNED_MATERIAL { get; set; }
        public string BOM { get; set; }
        public string ROUTING { get; set; }
        public int BUILD_QUANTITY { get; set; }
        public string CUSTOMER_ORDER { get; set; }
        public System.DateTime PLANNED_START { get; set; }
        public System.DateTime PLANNED_COMPLETION { get; set; }
        public int PRIORITY { get; set; }
        public int RELEASE_QUANTITY { get; set; }
    
        public virtual ME_BOM ME_BOM { get; set; }
        public virtual ME_MATERIAL ME_MATERIAL { get; set; }
        public virtual ME_ROUTING ME_ROUTING { get; set; }
        public virtual ME_SHOP_ORDER_TYPE ME_SHOP_ORDER_TYPE { get; set; }
        public virtual ME_SHOP_ORDER_STATUS ME_SHOP_ORDER_STATUS { get; set; }
    }
}
