//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESimulationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_BOM_DETAILS
    {
        public int ID { get; set; }
        public string BOM { get; set; }
        public int SEQUENCE { get; set; }
        public string COMPONENT { get; set; }
        public string OPERATION { get; set; }
        public int ASSEMBLY_QUANTITY { get; set; }
    
        public virtual ME_BOM ME_BOM { get; set; }
        public virtual ME_MATERIAL ME_MATERIAL { get; set; }
        public virtual ME_OPERATION ME_OPERATION { get; set; }
    }
}
