//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESimulationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_ROUTING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ME_ROUTING()
        {
            this.ME_ROUTING_DETAILS = new HashSet<ME_ROUTING_DETAILS>();
            this.ME_SHOP_ORDER = new HashSet<ME_SHOP_ORDER>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int TYPE { get; set; }
        public int STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ME_ROUTING_DETAILS> ME_ROUTING_DETAILS { get; set; }
        public virtual ME_ROUTING_STATUS ME_ROUTING_STATUS { get; set; }
        public virtual ME_ROUTING_TYPE ME_ROUTING_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ME_SHOP_ORDER> ME_SHOP_ORDER { get; set; }
    }
}
