//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESimulationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_SEMANTIC_ANNOTATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ME_SEMANTIC_ANNOTATION()
        {
            this.ME_ROUTING_DETAILS = new HashSet<ME_ROUTING_DETAILS>();
        }
    
        public int ID { get; set; }
        public string IRI { get; set; }
        public string SHORT_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ME_ROUTING_DETAILS> ME_ROUTING_DETAILS { get; set; }
    }
}
