//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESimulationService.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManufacturingExecutionEntities : DbContext
    {
        public ManufacturingExecutionEntities()
            : base("name=ManufacturingExecutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ME_ACTIVITY> ME_ACTIVITY { get; set; }
        public virtual DbSet<ME_BOM> ME_BOM { get; set; }
        public virtual DbSet<ME_BOM_DETAILS> ME_BOM_DETAILS { get; set; }
        public virtual DbSet<ME_BOM_STATUS> ME_BOM_STATUS { get; set; }
        public virtual DbSet<ME_MATERIAL> ME_MATERIAL { get; set; }
        public virtual DbSet<ME_MATERIAL_STATUS> ME_MATERIAL_STATUS { get; set; }
        public virtual DbSet<ME_MATERIAL_TYPE> ME_MATERIAL_TYPE { get; set; }
        public virtual DbSet<ME_OPERATION> ME_OPERATION { get; set; }
        public virtual DbSet<ME_OPERATION_STATUS> ME_OPERATION_STATUS { get; set; }
        public virtual DbSet<ME_OPERATION_TYPE> ME_OPERATION_TYPE { get; set; }
        public virtual DbSet<ME_RESOURCE> ME_RESOURCE { get; set; }
        public virtual DbSet<ME_RESOURCE_STATUS> ME_RESOURCE_STATUS { get; set; }
        public virtual DbSet<ME_RESOURCE_TYPE> ME_RESOURCE_TYPE { get; set; }
        public virtual DbSet<ME_ROUTING> ME_ROUTING { get; set; }
        public virtual DbSet<ME_ROUTING_DETAILS> ME_ROUTING_DETAILS { get; set; }
        public virtual DbSet<ME_ROUTING_STATUS> ME_ROUTING_STATUS { get; set; }
        public virtual DbSet<ME_ROUTING_TYPE> ME_ROUTING_TYPE { get; set; }
        public virtual DbSet<ME_SEMANTIC_ANNOTATION> ME_SEMANTIC_ANNOTATION { get; set; }
        public virtual DbSet<ME_SETPOINT> ME_SETPOINT { get; set; }
        public virtual DbSet<ME_SETPOINT_DETAILS> ME_SETPOINT_DETAILS { get; set; }
        public virtual DbSet<ME_SETPOINT_STATUS> ME_SETPOINT_STATUS { get; set; }
        public virtual DbSet<ME_SETPOINT_TYPE> ME_SETPOINT_TYPE { get; set; }
        public virtual DbSet<ME_SHOP_ORDER> ME_SHOP_ORDER { get; set; }
        public virtual DbSet<ME_SHOP_ORDER_STATUS> ME_SHOP_ORDER_STATUS { get; set; }
        public virtual DbSet<ME_SHOP_ORDER_TYPE> ME_SHOP_ORDER_TYPE { get; set; }
        public virtual DbSet<ME_WORKCENTER> ME_WORKCENTER { get; set; }
        public virtual DbSet<ME_WORKCENTER_CATEGORY> ME_WORKCENTER_CATEGORY { get; set; }
        public virtual DbSet<ME_WORKCENTER_RESOURCE> ME_WORKCENTER_RESOURCE { get; set; }
        public virtual DbSet<ME_WORKCENTER_STATUS> ME_WORKCENTER_STATUS { get; set; }
        public virtual DbSet<ME_WORKCENTER_TYPE> ME_WORKCENTER_TYPE { get; set; }
        public virtual DbSet<ME_RESOURCE_MATERIAL> ME_RESOURCE_MATERIAL { get; set; }
    }
}
