package testFactory;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: SomeConcept <br>
 * @version generated on Fri Sep 21 13:40:31 CEST 2018 by D065085
 */

public interface SomeConcept extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp1
     */
     
    /**
     * Gets all property values for the dp1 property.<p>
     * 
     * @returns a collection of values for the dp1 property.
     */
    Collection<? extends Object> getDp1();

    /**
     * Checks if the class has a dp1 property value.<p>
     * 
     * @return true if there is a dp1 property value.
     */
    boolean hasDp1();

    /**
     * Adds a dp1 property value.<p>
     * 
     * @param newDp1 the dp1 property value to be added
     */
    void addDp1(Object newDp1);

    /**
     * Removes a dp1 property value.<p>
     * 
     * @param oldDp1 the dp1 property value to be removed.
     */
    void removeDp1(Object oldDp1);



    /* ***************************************************
     * Property http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp2
     */
     
    /**
     * Gets all property values for the dp2 property.<p>
     * 
     * @returns a collection of values for the dp2 property.
     */
    Collection<? extends Object> getDp2();

    /**
     * Checks if the class has a dp2 property value.<p>
     * 
     * @return true if there is a dp2 property value.
     */
    boolean hasDp2();

    /**
     * Adds a dp2 property value.<p>
     * 
     * @param newDp2 the dp2 property value to be added
     */
    void addDp2(Object newDp2);

    /**
     * Removes a dp2 property value.<p>
     * 
     * @param oldDp2 the dp2 property value to be removed.
     */
    void removeDp2(Object oldDp2);



    /* ***************************************************
     * Property http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp3
     */
     
    /**
     * Gets all property values for the dp3 property.<p>
     * 
     * @returns a collection of values for the dp3 property.
     */
    Collection<? extends Object> getDp3();

    /**
     * Checks if the class has a dp3 property value.<p>
     * 
     * @return true if there is a dp3 property value.
     */
    boolean hasDp3();

    /**
     * Adds a dp3 property value.<p>
     * 
     * @param newDp3 the dp3 property value to be added
     */
    void addDp3(Object newDp3);

    /**
     * Removes a dp3 property value.<p>
     * 
     * @param oldDp3 the dp3 property value to be removed.
     */
    void removeDp3(Object oldDp3);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
