package testFactory;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Fri Sep 21 13:40:31 CEST 2018 by D065085
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#Concept
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SOMECONCEPT.<p>
     * 
     */
    public static final OWLClass CLASS_SOMECONCEPT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#Concept"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#sd
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SD = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#sd"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp1
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DP1.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DP1 = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp1"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp2
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DP2.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DP2 = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp2"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp3
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DP3.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DP3 = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/d065085/ontologies/2018/8/untitled-ontology-77#dp3"));


}
